baseURL = "https://<username>.github.io/"
languageCode = "en-us"
title = "ARW"
theme = "risotto"
[params]
  description = "Hi."
  year = "2024"
  darkModeEnabled = true  # Enable dark mode parameter
[module]
  [module.hugoVersion]
    min = "0.41.0"